# 1. Numpy Crash - Basic Numpy

In [1]:
import sys
import numpy as np
print("python {}".format(sys.version))
print("numpy {}".format(np.__version__))
sys.version
np.__version__

python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
numpy 1.16.2


'1.16.2'

In [2]:
# 스칼라
x = 6
x

6

In [3]:
# 벡터
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
print("vector dimension {}".format(x.shape))
print("vector size {}".format(x.size))

vector dimension (3,)
vector size 3


In [5]:
# matrix
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))

array dimension (3, 3)
array size 9


In [7]:
# 주어진 dimension 의 matrix 정의
x = np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print("array dimension {}".format(x.shape))
print("array size {}".format(x.size))

array dimension (2, 3)
array size 6


In [9]:
x = np.ones((3,3,3))
print(x)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
print("array dimension {}".format(x.shape))
print("array size {}".format(x.size))

array dimension (3, 3, 3)
array size 27


<img src="axes.png">

<img src="numpy.png" width="500">



<img src="tensor.jpg" width="600">

In [11]:
# indexing matrix
A = np.ones((5,5), dtype=np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
A[0]

array([1, 1, 1, 1, 1])

In [13]:
A[0,1] = 2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
A[:, 0] = 3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [15]:
A[:,:] = 5
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [16]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, :, 0] = 3
print(A)

[[[3 0 0]
  [3 0 0]
  [3 0 0]]

 [[3 0 0]
  [3 0 0]
  [3 0 0]]

 [[3 0 0]
  [3 0 0]
  [3 0 0]]]


In [17]:
A = np.zeros((3,3,3), dtype=np.int)
A[0, :, :] = 3
A[2,2,2] = 9
print(A)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 9]]]


In [18]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, 0, :] = 3
print(A)

[[[3 3 3]
  [0 0 0]
  [0 0 0]]

 [[3 3 3]
  [0 0 0]
  [0 0 0]]

 [[3 3 3]
  [0 0 0]
  [0 0 0]]]


In [19]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, 0, 0] = 3
print(A)

[[[3 0 0]
  [0 0 0]
  [0 0 0]]

 [[3 0 0]
  [0 0 0]
  [0 0 0]]

 [[3 0 0]
  [0 0 0]
  [0 0 0]]]


**matrix 연산**

In [20]:
# matrix operation
a = np.array(
    [[1,2], 
     [3,4]])
b = np.ones((2,2), dtype=np.int)
print(b, '\n')
print(a + b)

[[1 1]
 [1 1]] 

[[2 3]
 [4 5]]


In [21]:
print(a * b)

[[1 2]
 [3 4]]


In [22]:
print(a - b)

[[0 1]
 [2 3]]


In [23]:
print(np.matmul(a, b))

[[3 3]
 [7 7]]


In [24]:
print(a@b)

[[3 3]
 [7 7]]


In [25]:
print(a.dot(b))

[[3 3]
 [7 7]]


In [26]:
# matrix transpose
A = np.arange(9).reshape((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
print(A.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [28]:
A = np.array(range(10)).reshape((2,5))
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
B = A.T
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [30]:
print(A.shape)
print(B.shape)

(2, 5)
(5, 2)


In [31]:
print(np.c_[A, B.reshape(2,5)])

[[0 1 2 3 4 0 5 1 6 2]
 [5 6 7 8 9 7 3 8 4 9]]


**다차원 배열(array)을 1차원 배열로 변환**

In [32]:
print(A.ravel())
print(B.ravel())

[0 1 2 3 4 5 6 7 8 9]
[0 5 1 6 2 7 3 8 4 9]


In [33]:
# tensors
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A))
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
3
10
59049


## random value

np.random.random_sample  -  [0.0, 1.0)  사이의 random 숫자   
> alias : np.random.random


np.random.randn - 표준정규분포의 random 숫자



In [67]:
np.random.seed(10)

In [68]:
np.random.random_sample((3, 2))

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [69]:
np.random.random((3, 2))

array([[0.19806286, 0.76053071],
       [0.16911084, 0.08833981],
       [0.68535982, 0.95339335]])

In [70]:
np.random.rand(3, 2)

array([[0.00394827, 0.51219226],
       [0.81262096, 0.61252607],
       [0.72175532, 0.29187607]])

In [71]:
np.random.randn(3, 2)

array([[ 0.22863013,  0.44513761],
       [-1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489]])